helloWorld:
  image: luisbianconi/hello-world-go:c8f5910
  replicas: 2
  port: 8080
  imagePullPolicy: Always

service:
  type: ClusterIP
  port: 80
  targetPort: 8080

ingress:
  enabled: true
  className: "nginx"
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
  hosts:
    - host: dev.luisbianconi.com
      paths:
        - path: /
          pathType: Prefix
  tls: []
