helloWorld:
  image: luisbianconi/hello-world-go:23cb683
  replicas: 2
  port: 8080
  imagePullPolicy: Always

service:
  type: ClusterIP
  port: 80
  targetPort: 8080

ingress:
  enabled: true
  className: "nginx"
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
  hosts:
    - host: dev.luisbianconi.com
      paths:
        - path: /
          pathType: Prefix
  tls:
    - secretName: dev-luisbianconi-com-tls
      hosts:
        - dev.luisbianconi.com
