helloWorld:
  image: luisbianconi/hello-world-go:60788cc
  replicas: 2
  port: 8080
  imagePullPolicy: Always

service:
  type: ClusterIP
  port: 80
  targetPort: 8080

ingress:
  enabled: true
  className: "nginx"
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
    nginx.ingress.kubernetes.io/force-ssl-redirect: "false"
    cert-manager.io/acme-challenge-type: "http01"
  hosts:
    - host: prd.luisbianconi.com
      paths:
        - path: /
          pathType: Prefix
  tls:
    - secretName: prd-luisbianconi-com-tls
      hosts:
        - prd.luisbianconi.com
